language: scala

jdk:
  - openjdk11

jobs:
  include:
    - &scala_2.11
      stage: build and test
      scala:
        - 2.11.12
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean test
    - &scala_2.12
      stage: build and test
      scala:
        - 2.12.10
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - &scala_2.13
      stage: build and test
      scala:
        - 2.13.1
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot