language: scala

scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12

jdk:
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage
  - sbt ++$TRAVIS_SCALA_VERSION test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot